language: cpp

compiler:
      - gcc

before_install:
      - pwd
      - cd ../
      - pwd
      - mkdir builds
      - cd builds
      - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
      - sudo add-apt-repository --yes 'deb http://ppa.launchpad.net/canonical-x/x-staging/ubuntu precise main'
      - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
      - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test/ubuntu
      - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
      - sudo apt-get update -qq
      - sudo apt-get install qt5-default
      - sudo apt-get install cmake
      - sudo apt-get install libqt5webkit5-dev
      - wget -O OpenCV.zip  http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip 
      - unzip OpenCV 
      - cd opencv-2.4.9 
      - mkdir build 
      - cd build 
      - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_TESTS=OFF ..
      - make -j10
      - sudo make install
      - cd ../../
      - sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
      - sudo apt-get install libxt-dev
      - git clone http://github.com/Kitware/VTK -b v6.1.0
      - cd VTK
      - mkdir Build
      - cd Build
      - cmake -D BUILD_SHARED_LIBS=OFF -D BUILD_TESTING=OFF -D CMAKE_BUILD_TYPE=RELEASE -D VTK_GROUP_QT=ON -D VTK_QT_VERSION=5 ..
      - make -j10
      - sudo make install
      - pwd
      - cd ../../
      - cd ../
      - cd PhD-Thesis
      - pwd

before_script:
      - mkdir build
      - cd build
      - cmake ..

script: make

cache: apt
