#############################################################################
# Makefile for building: build/debug/PhD-Thesis.app/Contents/MacOS/PhD-Thesis
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  PhD-Thesis.pro
# Template: app
# Command: /opt/local/bin/qmake -o Makefile PhD-Thesis.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/local/share/qt5/mkspecs/macx-clang -I. -I. -I/opt/local/Library/Frameworks/QtWidgets.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtGui.framework/Versions/5/Headers -I/opt/local/Library/Frameworks/QtCore.framework/Versions/5/Headers -Ibuild/debug/.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/opt/local/Library/Frameworks
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/opt/local/Library/Frameworks -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /opt/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = main.cpp 
OBJECTS       = build/debug/.obj/main.o
DIST          = /opt/local/share/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/share/qt5/mkspecs/qdevice.pri \
		/opt/local/share/qt5/mkspecs/features/device_config.prf \
		/opt/local/share/qt5/mkspecs/common/shell-unix.conf \
		/opt/local/share/qt5/mkspecs/common/unix.conf \
		/opt/local/share/qt5/mkspecs/common/mac.conf \
		/opt/local/share/qt5/mkspecs/common/macx.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/share/qt5/mkspecs/common/clang.conf \
		/opt/local/share/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/share/qt5/mkspecs/qconfig.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/share/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt5/mkspecs/features/qt_config.prf \
		/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt5/mkspecs/features/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/share/qt5/mkspecs/features/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt5/mkspecs/features/warn_on.prf \
		/opt/local/share/qt5/mkspecs/features/qt.prf \
		/opt/local/share/qt5/mkspecs/features/resources.prf \
		/opt/local/share/qt5/mkspecs/features/moc.prf \
		/opt/local/share/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/share/qt5/mkspecs/features/uic.prf \
		/opt/local/share/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/share/qt5/mkspecs/features/exceptions.prf \
		/opt/local/share/qt5/mkspecs/features/yacc.prf \
		/opt/local/share/qt5/mkspecs/features/lex.prf \
		PhD-Thesis.pro main.cpp
QMAKE_TARGET  = PhD-Thesis
DESTDIR       = build/debug/#avoid trailing-slash linebreak
TARGET        = build/debug/PhD-Thesis.app/Contents/MacOS/PhD-Thesis

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build/debug/PhD-Thesis.app/Contents/PkgInfo build/debug/PhD-Thesis.app/Contents/Resources/empty.lproj build/debug/PhD-Thesis.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d build/debug/PhD-Thesis.app/Contents/MacOS/ || mkdir -p build/debug/PhD-Thesis.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PhD-Thesis.pro /opt/local/share/qt5/mkspecs/macx-clang/qmake.conf /opt/local/share/qt5/mkspecs/features/spec_pre.prf \
		/opt/local/share/qt5/mkspecs/qdevice.pri \
		/opt/local/share/qt5/mkspecs/features/device_config.prf \
		/opt/local/share/qt5/mkspecs/common/shell-unix.conf \
		/opt/local/share/qt5/mkspecs/common/unix.conf \
		/opt/local/share/qt5/mkspecs/common/mac.conf \
		/opt/local/share/qt5/mkspecs/common/macx.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base.conf \
		/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/opt/local/share/qt5/mkspecs/common/clang.conf \
		/opt/local/share/qt5/mkspecs/common/clang-mac.conf \
		/opt/local/share/qt5/mkspecs/qconfig.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/share/qt5/mkspecs/features/qt_functions.prf \
		/opt/local/share/qt5/mkspecs/features/qt_config.prf \
		/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf \
		/opt/local/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/local/share/qt5/mkspecs/features/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf \
		/opt/local/share/qt5/mkspecs/features/resolve_config.prf \
		/opt/local/share/qt5/mkspecs/features/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/sdk.prf \
		/opt/local/share/qt5/mkspecs/features/mac/default_post.prf \
		/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf \
		/opt/local/share/qt5/mkspecs/features/warn_on.prf \
		/opt/local/share/qt5/mkspecs/features/qt.prf \
		/opt/local/share/qt5/mkspecs/features/resources.prf \
		/opt/local/share/qt5/mkspecs/features/moc.prf \
		/opt/local/share/qt5/mkspecs/features/unix/opengl.prf \
		/opt/local/share/qt5/mkspecs/features/uic.prf \
		/opt/local/share/qt5/mkspecs/features/unix/thread.prf \
		/opt/local/share/qt5/mkspecs/features/mac/rez.prf \
		/opt/local/share/qt5/mkspecs/features/testcase_targets.prf \
		/opt/local/share/qt5/mkspecs/features/exceptions.prf \
		/opt/local/share/qt5/mkspecs/features/yacc.prf \
		/opt/local/share/qt5/mkspecs/features/lex.prf \
		PhD-Thesis.pro \
		/opt/local/Library/Frameworks/QtWidgets.framework/QtWidgets.prl \
		/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl \
		/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile PhD-Thesis.pro
/opt/local/share/qt5/mkspecs/features/spec_pre.prf:
/opt/local/share/qt5/mkspecs/qdevice.pri:
/opt/local/share/qt5/mkspecs/features/device_config.prf:
/opt/local/share/qt5/mkspecs/common/shell-unix.conf:
/opt/local/share/qt5/mkspecs/common/unix.conf:
/opt/local/share/qt5/mkspecs/common/mac.conf:
/opt/local/share/qt5/mkspecs/common/macx.conf:
/opt/local/share/qt5/mkspecs/common/gcc-base.conf:
/opt/local/share/qt5/mkspecs/common/gcc-base-mac.conf:
/opt/local/share/qt5/mkspecs/common/clang.conf:
/opt/local/share/qt5/mkspecs/common/clang-mac.conf:
/opt/local/share/qt5/mkspecs/qconfig.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/local/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/local/share/qt5/mkspecs/features/qt_functions.prf:
/opt/local/share/qt5/mkspecs/features/qt_config.prf:
/opt/local/share/qt5/mkspecs/macx-clang/qmake.conf:
/opt/local/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/local/share/qt5/mkspecs/features/exclusive_builds.prf:
/opt/local/share/qt5/mkspecs/features/default_pre.prf:
/opt/local/share/qt5/mkspecs/features/mac/default_pre.prf:
/opt/local/share/qt5/mkspecs/features/resolve_config.prf:
/opt/local/share/qt5/mkspecs/features/default_post.prf:
/opt/local/share/qt5/mkspecs/features/mac/sdk.prf:
/opt/local/share/qt5/mkspecs/features/mac/default_post.prf:
/opt/local/share/qt5/mkspecs/features/mac/objective_c.prf:
/opt/local/share/qt5/mkspecs/features/warn_on.prf:
/opt/local/share/qt5/mkspecs/features/qt.prf:
/opt/local/share/qt5/mkspecs/features/resources.prf:
/opt/local/share/qt5/mkspecs/features/moc.prf:
/opt/local/share/qt5/mkspecs/features/unix/opengl.prf:
/opt/local/share/qt5/mkspecs/features/uic.prf:
/opt/local/share/qt5/mkspecs/features/unix/thread.prf:
/opt/local/share/qt5/mkspecs/features/mac/rez.prf:
/opt/local/share/qt5/mkspecs/features/testcase_targets.prf:
/opt/local/share/qt5/mkspecs/features/exceptions.prf:
/opt/local/share/qt5/mkspecs/features/yacc.prf:
/opt/local/share/qt5/mkspecs/features/lex.prf:
PhD-Thesis.pro:
/opt/local/Library/Frameworks/QtWidgets.framework/QtWidgets.prl:
/opt/local/Library/Frameworks/QtGui.framework/QtGui.prl:
/opt/local/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile PhD-Thesis.pro

qmake_all: FORCE

build/debug/PhD-Thesis.app/Contents/PkgInfo: 
	@test -d build/debug/PhD-Thesis.app/Contents || mkdir -p build/debug/PhD-Thesis.app/Contents
	@$(DEL_FILE) build/debug/PhD-Thesis.app/Contents/PkgInfo
	@echo "APPL????" >build/debug/PhD-Thesis.app/Contents/PkgInfo
build/debug/PhD-Thesis.app/Contents/Resources/empty.lproj: 
	@test -d build/debug/PhD-Thesis.app/Contents/Resources || mkdir -p build/debug/PhD-Thesis.app/Contents/Resources
	@touch build/debug/PhD-Thesis.app/Contents/Resources/empty.lproj
	
build/debug/PhD-Thesis.app/Contents/Info.plist: 
	@test -d build/debug/PhD-Thesis.app/Contents || mkdir -p build/debug/PhD-Thesis.app/Contents
	@$(DEL_FILE) build/debug/PhD-Thesis.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,teste.PhD-Thesis,g" -e "s,@EXECUTABLE@,PhD-Thesis,g" -e "s,@TYPEINFO@,????,g" /opt/local/share/qt5/mkspecs/macx-clang/Info.plist.app >build/debug/PhD-Thesis.app/Contents/Info.plist
dist: 
	@test -d build/debug/.obj/PhD-Thesis1.0.0 || mkdir -p build/debug/.obj/PhD-Thesis1.0.0
	$(COPY_FILE) --parents $(DIST) build/debug/.obj/PhD-Thesis1.0.0/ && $(COPY_FILE) --parents main.cpp build/debug/.obj/PhD-Thesis1.0.0/ && (cd `dirname build/debug/.obj/PhD-Thesis1.0.0` && $(TAR) PhD-Thesis1.0.0.tar PhD-Thesis1.0.0 && $(COMPRESS) PhD-Thesis1.0.0.tar) && $(MOVE) `dirname build/debug/.obj/PhD-Thesis1.0.0`/PhD-Thesis1.0.0.tar.gz . && $(DEL_FILE) -r build/debug/.obj/PhD-Thesis1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r build/debug/PhD-Thesis.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/debug/.obj/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

