# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wachs/Implementacao

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wachs/Implementacao

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wachs/Implementacao/CMakeFiles /Users/wachs/Implementacao/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wachs/Implementacao/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-cmake-files

# Build rule for target.
clean-cmake-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-cmake-files
.PHONY : clean-cmake-files

# fast build rule for target.
clean-cmake-files/fast:
	$(MAKE) -f CMakeFiles/clean-cmake-files.dir/build.make CMakeFiles/clean-cmake-files.dir/build
.PHONY : clean-cmake-files/fast

#=============================================================================
# Target rules for targets named ComplexNetwork

# Build rule for target.
ComplexNetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ComplexNetwork
.PHONY : ComplexNetwork

# fast build rule for target.
ComplexNetwork/fast:
	$(MAKE) -f SOURCES/ComplexNetwork/CMakeFiles/ComplexNetwork.dir/build.make SOURCES/ComplexNetwork/CMakeFiles/ComplexNetwork.dir/build
.PHONY : ComplexNetwork/fast

#=============================================================================
# Target rules for targets named NetworkConstructionTest

# Build rule for target.
NetworkConstructionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NetworkConstructionTest
.PHONY : NetworkConstructionTest

# fast build rule for target.
NetworkConstructionTest/fast:
	$(MAKE) -f SOURCES/Tests/CMakeFiles/NetworkConstructionTest.dir/build.make SOURCES/Tests/CMakeFiles/NetworkConstructionTest.dir/build
.PHONY : NetworkConstructionTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... clean-cmake-files"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ComplexNetwork"
	@echo "... NetworkConstructionTest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

