######################################################################
# Automatically generated by qmake (3.0) ter set 16 20:06:19 2014
######################################################################

QT+=core
QT+=widgets
TEMPLATE = app
TARGET = PhdThesis
INCLUDEPATH += .

# Input
SOURCES += main.cpp
